### ISSUE TITLE
envkey-source crashes with the "--verbose" flag

### ISSUE THREAD

**Issue by ndbroadbent** [envkey/envkey-source#12]
```
$ envkey-source --verbose
Initializing cache at panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12b2f1e]

goroutine 1 [running]:
github.com/envkey/envkey-fetch/fetch.Fetch(0xc4200205d7, 0x25, 0x1, 0x0, 0x0, 0x13c789c, 0xd, 0x13c57a7, 0x5, 0x1, ...)
	/Users/daneschneider/go/src/github.com/envkey/envkey-fetch/fetch/fetch.go:77 +0x49e
github.com/envkey/envkey-source/shell.Source(0xc4200205d7, 0x25, 0xc420020500, 0x1, 0x0, 0x0, 0x13c789c, 0xd, 0x13c57a7, 0x5, ...)
	/Users/daneschneider/go/src/github.com/envkey/envkey-source/shell/shell.go:17 +0x86
github.com/envkey/envkey-source/cmd.glob..func1(0x1607360, 0xc420074c90, 0x0, 0x1)
	/Users/daneschneider/go/src/github.com/envkey/envkey-source/cmd/root.go:79 +0x2cc
github.com/spf13/cobra.(*Command).execute(0x1607360, 0xc42000a090, 0x1, 0x1, 0x1607360, 0xc42000a090)
	/Users/daneschneider/go/src/github.com/spf13/cobra/command.go:651 +0x23d
github.com/spf13/cobra.(*Command).ExecuteC(0x1607360, 0xc42006bf58, 0x13019fc, 0xc42011c0f0)
	/Users/daneschneider/go/src/github.com/spf13/cobra/command.go:726 +0x2d4
github.com/spf13/cobra.(*Command).Execute(0x1607360, 0xc42002a118, 0x0)
	/Users/daneschneider/go/src/github.com/spf13/cobra/command.go:685 +0x2b
github.com/envkey/envkey-source/cmd.Execute()
	/Users/daneschneider/go/src/github.com/envkey/envkey-source/cmd/root.go:87 +0x2d
main.main()
	/Users/daneschneider/go/src/github.com/envkey/envkey-source/main.go:28 +0x20
```

**Comment by ndbroadbent** [comment]
It might also be good idea to set something like [GOROOT_FINAL=/usr/go](https://github.com/golang/go/issues/13809) if you want to remove "/Users/daneschneider/go/src" from the stack traces (but not a big deal.)

**Comment by danenania** [comment]
Good catch--this was likely introduced in the latest release. I should
probably throw in a test with the verbose flag set.

Also good idea on cleaning up stack traces!

**Comment by ndbroadbent** [comment]
Oh actually if you haven't started on this, I'd be happy to take a look to see if I can fix it and add a test. Better to send a PR than an issue!

**Comment by danenania** [comment]
I actually just found the problem, which is in envkey-fetch--trying to
output an error that is nil. I'm just about to push up a new release.
Thanks though!
