### ISSUE TITLE
Failing inside docker images running on Apple M1

### ISSUE THREAD

**Issue by Pedrobc89** [envkey/envkey-source#19]
#Description
When running the following command on a Docker image builded inside a Apple M1
```
RUN curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | bash
```
Output error:
```
=> ERROR [ 2/11] RUN curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | bash                                          3.7s
------                                                                                                                                                      
 > [ 2/11] RUN curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | bash:                                                     
#5 1.462 envkey-source 1.2.10 Quick Install                                                                                                                 
#5 1.462 Copyright (c) 2021 Envkey Inc. - MIT License                                                                                                       
#5 1.462 https://github.com/envkey/envkey-source                                                                                                            
#5 1.462                                                                                                                                                    
#5 1.462 Downloading envkey-source binary for linux-386
#5 1.462 Downloading tarball from Github Releases: https://github.com/envkey/envkey-source/releases/download/v1.2.10/envkey-source_1.2.10_linux_386.tar.gz
#5 3.556 envkey-source is installed in /usr/local/bin
#5 3.557 Installation complete. Info:
#5 3.557 
#5 3.577 fatal error: unexpected signal during runtime execution
#5 3.585 [signal SIGSEGV: segmentation violation code=0x1 addr=0x720 pc=0x8087c8a]
#5 3.585 
#5 3.585 runtime stack:
#5 3.586 runtime.throw(0x83c29aa, 0x2a)
#5 3.586        /usr/go/src/runtime/panic.go:1117 +0x6a
#5 3.586 runtime.sigpanic()
#5 3.586        /usr/go/src/runtime/signal_unix.go:718 +0x23f
#5 3.586 runtime.runqput(0x0, 0x8800380, 0x1)
#5 3.587        /usr/go/src/runtime/proc.go:5746 +0x2a
#5 3.587 runtime.newproc.func1()
#5 3.587        /usr/go/src/runtime/proc.go:3982 +0x66
#5 3.587 runtime.systemstack(0x80a6464)
#5 3.587        /usr/go/src/runtime/asm_386.s:391 +0x53
#5 3.587 runtime.mstart()
#5 3.587        /usr/go/src/runtime/proc.go:1246
#5 3.587 
#5 3.587 goroutine 1 [running, locked to thread]:
#5 3.587        goroutine running on other thread; stack unavailable
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | bash]: exit code: 2
```

I was able  to confirm that the `envkey-source` gets installed. But running `envkey-source -h` is when the error pops.

After looking on the script, I noticed that `uname -m` was not on the list.
By adding the following lines we solved the error locally.
```
elif [[ "$(uname -m)" == 'aarch64' ]]; then
  ARCH="arm64"
```

Synce Apple M1 is an arm processor, we could get the envkey working.

**Comment by danenania** [comment]
Thanks Pedro for the detailed bug report and finding a fix. We'll incorporate this shortly!
